### PR TITLE
Updated privacy considerations

### LINKED ISSUE #58: HDCP Privacy Considerations
https://github.com/WICG/media-capabilities/blob/master/eme-extension-policy-check.md says:
> As access to this API is gated by requestMediaKeySystemAccess(), use of this API may require user consent (e.g., prompt), if required by the user agent for the configuration. This should make it more difficult to abuse the API on those user agents.

The `may` statement is true. For instance, in ChromeOS, this code below doesn't trigger a prompt as of now:

```js
const config = [{
  videoCapabilities: [{
    contentType: 'video/webm; codecs="vp9"',
    robustness: 'SW_SECURE_DECODE'
  }]
}];

await navigator.requestMediaKeySystemAccess('com.widevine.alpha', config)
````

This means websites can easily get user HDCP versions. I would remove the last paragraph as other user agents for now (Edge and Firefox) don't even show a prompt at all.

### PR DESCRIPTION
**Pull request by beaufortfrancois**
Fix #58

### CODE REVIEW

**Comment by mounirlamouri** [comment]
lgtm, thanks! :)

**Comment by mwatson2** [comment]
I think this PR was proposed and merged within the space of a few minutes. That’s a bit fast for proper review.

I think it’s a bit of an overstatement to say the privacy considerations of this API are the same as for EME. This API introduces a few bits at most of entropy, especially considering that for laptops at least they are plugged in and out of external displays. By contrast, EME privacy considerations have to deal with distinctive identifiers, which are much more serious.

Could we have time for discussion before things are merged ?

**Comment by mounirlamouri** [comment]
@mwatson2 sorry about this. François has the benefit of being in my timezone and have direct access to me which made this go unusually fast ;)

I tried to revert the change but because we had other changes on top of it, GitHub tries to revert a few other changes with it. Would you have recommended wording for François to use?

**Comment by mwatson2** [comment]
Here is a suggestion for the whole section:

"This would allow an application to discover whether the device is connected to an HDCP-capable display and the version of HDCP that has been negotiated. HDCP is widely available on most modern operating systems and display types. In some use-cases (e.g. laptops) displays are often connected and disconnected over time. It is therefore not expected to add much entropy for fingerprinting.

Access to this API is gated by the async requestMediaKeySystemAccess() which may require user content."

**Comment by mounirlamouri** [comment]
@beaufortfrancois WDYT?

**Comment by beaufortfrancois** [comment]
LGTM

**Pull request merged**
